# Fyers API Credentials
APP_ID = "WQPNJZHYO1-100"  # Replace with your App ID
SECRET_KEY = "PUF02F01IT"  # Replace with your Secret Key
REDIRECT_URI = "https://www.google.com"  # Replace with your Redirect URI

# Strategy Toggle
STRATEGY = "MMR"  # "EMA_CROSSOVER" or "MMR"

# EMA Crossover Strategy Parameters (Crude Oil)
SYMBOL_UNDERLYING = "MCX:CRUDEOILM26FEBFUT"
SYMBOL_EXPIRY = "26FEB"
TIME_FRAME = "5"
EMA_FAST = 9
EMA_SLOW = 21

# MMR Strategy Parameters
MMR_INTERVAL = "15"
MMR_INDEX_SYMBOL = "NSE:NIFTY50-INDEX"
MMR_GAP_PCT = 0.5
MMR_ATR_TRIGGER_MULT = 0.6
MMR_SL_ATR_MULT = 1.2
MMR_TARGET_ATR_MULT = 2.0
MAX_CAPITAL = 100000
RISK_PER_TRADE_PCT = 0.01

MMR_STOCKS = [
    "NSE:AARTIDRUGS-EQ", "NSE:AFFLE-EQ", "NSE:AMBER-EQ", "NSE:ASTERDM-EQ", "NSE:ATUL-EQ",
    "NSE:AVANTIFEED-EQ", "NSE:BASF-EQ", "NSE:BDL-EQ", "NSE:BSOFT-EQ", "NSE:CAMS-EQ",
    "NSE:CDSL-EQ", "NSE:CREDITACC-EQ", "NSE:CYIENT-EQ", "NSE:DEEPAKNTR-EQ", "NSE:ERIS-EQ",
    "NSE:FINEORG-EQ", "NSE:GMMPFAUDLR-EQ", "NSE:GRANULES-EQ", "NSE:HAPPSTMNDS-EQ",
    "NSE:IEX-EQ", "NSE:INDIAMART-EQ", "NSE:IRB-EQ", "NSE:JBCHEPHARM-EQ", "NSE:JUBLFOOD-EQ",
    "NSE:KNRCON-EQ", "NSE:LALPATHLAB-EQ", "NSE:MCX-EQ", "NSE:METROPOLIS-EQ", "NSE:NAVINFLUOR-EQ",
    "NSE:NBCC-EQ", "NSE:OBEROIRLTY-EQ", "NSE:OLECTRA-EQ", "NSE:PFIZER-EQ", "NSE:PNCINFRA-EQ",
    "NSE:RVNL-EQ", "NSE:SONATSOFTW-EQ", "NSE:STAR-EQ", "NSE:SUPREMEIND-EQ", "NSE:TATACOMM-EQ",
    "NSE:TATAELXSI-EQ", "NSE:TRENT-EQ"
]

# Trading Parameters
LOT_SIZE = 1  # For EMA Crossover
STOP_LOSS_PCT = 0.5  # For EMA Crossover
TARGET_PCT = 1.0  # For EMA Crossover

# File paths
TOKEN_FILE = "access_token.txt"
